title: Trevor's University of Essex ePortfolio
description: >- # this means to ignore newlines until "baseurl:"

domain: "essex.trevorwoodman.ca"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://essex.trevorwoodman.ca" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
