#!/usr/bin/env bash

GIT_REPO=$HOME/essex.git
TMP_GIT_CLONE=/tmp/essex
PUBLIC_WWW=/var/www/essex.trevorwoodman.ca

git clone $GIT_REPO $TMP_GIT_CLONE
pushd $TMP_GIT_CLONE
bundle exec jekyll build -d $PUBLIC_WWW
popd
rm -rf $TMP_GIT_CLONE

exit
